services:
  snake-game-score-service:
    container_name: snake-game-score-service
    image: ghcr.io/lockhart07/snake-game:latest
    pull_policy: always
    tty: true
    stdin_open: true
    ports:
      - "8000:8000"
    volumes:
      # attach the relative directory 'data' to the container's /data path
      - /mnt/snake-game:/data
    healthcheck:
      test: curl --fail http://localhost:8000/snake-game/api/ping || exit 1
      interval: 40s
      timeout: 30s
      retries: 3
      start_period: 60s