services:
  snake-game-score-service:
    container_name: snake-game-score-service
    image: ghcr.io/lockhart07/snake-game:latest
    pull_policy: always
    tty: true
    stdin_open: true
    ports:
      - "8000:8000"
    volumes:
      # attach the relative directory 'data' to the container's /data path
      - /mnt/snake-game:/data
    healthcheck:
      test: ["CMD", "python3", "-c", "import socket; s=socket.socket(); s.settimeout(5); s.connect(('localhost', 8000)); s.close()"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
