name: Build Vue
on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue
    steps:
      - uses: actions/checkout@v2
      - name: Do everything
        run: |
          cd frontend
          npm install
          npm run build
          cd dist
          git config --global user.email "dsouzajenslee@gmail.com"
          git config --global user.name "Jenslee"
          git init
          git add -A
          git commit -m 'Commiting for build'
          git push -f https://LOCKhart07:${{ secrets.GITHUB_TOKEN }}@github.com/LOCkhart07/snake-game.git master:gh-pages
