name: Build Vue
on: [push]
jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue
    steps:
      - uses: actions/checkout@v2
      - name: Do everything
        run: |
          cd frontend
          npm install
          npm run build
          cd dist
          git config --global user.email "dsouzajenslee@gmail.com"
          git config --global user.name "Jenslee"
          git init
          git add -A
          git commit -m 'Commiting for build'
          git push -f https://LOCKhart07:${{ secrets.GITHUB_TOKEN }}@github.com/LOCkhart07/snake-game.git master:gh-pages
